[general]
import = [
"~/.config/alacritty/themes/catppuccin-macchiato.toml",
#"~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[window]
opacity = 0.7
blur = true
startup_mode = "Fullscreen"
# decorations = "Buttonless"
option_as_alt = "Both"

[scrolling]
history = 100000

[font]
size = 17
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/opt/homebrew/bin/zellij"
